name: Manage builds and version

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_NAME: github_actions
  USER_MAIL: actions@github.com

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npm run release

  merge_release:
    needs: [release]
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set git config
        run: |
          git config --local user.email ${{env.USER_MAIL}}
          git config --local user.name ${{env.USER_NAME}}

      - name: Merge ${{env.FROM_BRANCH}} and push to ${{env.TO_BRANCH}}
        run: |
          git fetch
          git checkout ${{env.TO_BRANCH}}
          git pull
          git merge ${{env.FROM_BRANCH}} -m "Auto-merge ${{env.FROM_BRANCH}} to ${{env.TO_BRANCH}}"
          git push
